[package]
name = "taik"
version = "0.0.1"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"
repository = "https://github.com/MortenLohne/taik/"
readme = "README.md"
license = "GPL-3.0-or-later"

[profile.release]
debug = true

[features]
constant-tuning = ["rayon", "log", "nom"]

[dependencies]
board-game-traits = "0.1"
pgn-traits = "0.1"
smallvec = "1.2"
rand = "0.7"
arrayvec = "0.5.1"
rayon = { version = "1.3.*", optional = true }
log = { version = "0.4.8", optional = true }

[dependencies.nom]
version = "4.2"
features = ["verbose-errors"]
optional = true