[package]
name = "taik"
version = "0.0.1"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"
repository = "https://github.com/MortenLohne/taik/"
readme = "README.md"
license = "GPL-3.0-or-later"

[profile.release]
debug = true

[dependencies]
board-game-traits = "0.1"
pgn-traits = "0.1"
smallvec = "1.2"
rand = "0.7"
arrayvec = "0.5.1"
rayon = "1.3.*"
log = "0.4.8"

[dependencies.nom]
version = "4.2"
features = ["verbose-errors"]