[package]
name = "taik"
version = "0.1.0"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"
repository = "https://github.com/MortenLohne/taik/"
readme = "README.md"
license = "GPL-3.0-or-later"
default-run = "main"

[profile.release]
debug = true

[features]
pgn-writer = []
constant-tuning = ["rayon", "nom", "pgn-writer"]
aws-lambda = ["lambda_runtime", "serde", "arrayvec/serde"]

[[bin]]
name = "aws_lambda"
required-features = ["aws-lambda"]

[dependencies]
board-game-traits = "0.1"
pgn-traits = "0.1"
rand = "0.7"
arrayvec = "0.5.1"
rayon = { version = "1.3.*", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
lambda_runtime = { version = "0.2.1", optional = true }
log = "0.4"
fern = "0.5"
chrono = "0.4"
bufstream = "0.1"
clap = "2.33"

[dependencies.nom]
version = "4.2"
features = ["verbose-errors"]
optional = true